### ISSUE TITLE
ImportError: No module named pandas_bokeh

### ISSUE THREAD

**Issue by gollima** [Azure/Azure-Sentinel-Notebooks#12]
Getting this error on using the Linux notebook.

Importing python packages....

ImportErrorTraceback (most recent call last)

<ipython-input-1-f2ad9987aa82> in <module>()
      4 import re
      5 import pandas as pd
----> 6 import pandas_bokeh
      7 pandas_bokeh.output_notebook()
      8 import numpy as np

ImportError: No module named pandas_bokeh

**Comment by petebryan** [comment]
Hi @gollima 

This is likely due to the fact you don't have pandas_bokeh installed in your environment. We have included a setup cell at the bottom of the Notebook that you can run the first time you use the Notebook, this will install pandas_bokeh (as well as other packages the Notebook needs). Once you have run that cell scroll back up to the top and run the import cell again.

![image](https://user-images.githubusercontent.com/8940401/76338589-20ad0000-62b6-11ea-94cf-7f73b04b7817.png)

**Comment by petebryan** [comment]
Hi @gollima.

I'll close this for now. If you are still having issues please let us know.
